

const userActionTypes = {
    TRY_TO_LOGIN: 'TRY_TO_LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    TRY_TO_REGISTER: 'TRY_TO_REGISTER',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE',

};

export default userActionTypes;