
const productActionTypes = {
    FETCH_ALL_STARTS:'FETCH_ALL_STARTS',
    FETCH_ALL_SUCCESS:'FETCH_ALL_SUCCESS',
    FETCH_ALL_FAILURE:'FETCH_ALL_FAILURE',
    FETCH_ONE_STARTS:'FETCH_ONE_STARTS',
    FETCH_ONE_SUCCESS:'FETCH_ONE_SUCCESS',
    FETCH_ONE_FAILURE:'FETCH_ONE_FAILURE',
}

export default productActionTypes;