const cartActionTypes = {
    ADD_TO_CART_START:'ADD_TO_CART_START',
    ADD_TO_CART_SUCCESS:'ADD_TO_CART_SUCCESS',
    ADD_TO_CART_FAILURE:'ADD_TO_CART_FAILURE',
    FETCH_ITEMS_START: 'FETCH_ITEMS_START',
    FETCH_ITEMS_SUCCESS: 'FETCH_ITEMS_SUCCESS',
    FETCH_ITEMS_FAILURE: 'FETCH_ITEMS_FAILURE',
    REMOVE_ITEM_START: 'REMOVE_ITEM_START',
    REMOVE_ITEM_SUCCESS: 'REMOVE_ITEM_SUCCESS',
    REMOVE_ITEM_FAILURE: 'REMOVE_ITEM_FAILURE',
};

export default cartActionTypes;