const cartActionTypes = {
    ADD_TO_CART_START:'ADD_TO_CART_START',
    ADD_TO_CART_SUCCESS:'ADD_TO_CART_SUCCESS',
    ADD_TO_CART_FAILURE:'ADD_TO_CART_FAILURE',
    FETCH_ITEMS_START: 'FETCH_ITEMS_START',
    FETCH_ITEMS_SUCCESS: 'FETCH_ITEMS_SUCCESS',
    FETCH_ITEMS_FAILURE: 'FETCH_ITEMS_FAILURE',
};

export default cartActionTypes;